# Generated by Django 5.2.7 on 2026-01-19 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_report_location_report_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('moderator', 'Moderator')], default='citizen', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.FloatField(db_default=0.0, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.FloatField(db_default=0.0, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
