# Generated by Django 5.2.7 on 2026-01-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_role_alter_report_latitude_and_more'),
        ('api', '0008_report_location_alter_comment_created_at_and_more'),
    ]

    operations = [
    ]
