# Generated by Django 5.2.7 on 2026-01-27 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20260127_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportstatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='reportstatus',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='reportstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportstatus',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='api.report'),
        ),
    ]
